language: cpp

compiler:
  - g++
  - clang++

script:
  - git submodule update --init --recursive
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - cmake --build . --config -j8
  - ./bin/tests/tests

notifications:
  email: false
