environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_GENERATOR: "Visual Studio 16 2019"

build_script:
  - cmd: git submodule update --init --recursive
  - cmd: if exist build\ rmdir /s /q build\
  - cmd: mkdir build && cd build
  - cmd: cmake ..
  - cmd: cmake --build . --config Release
  - cmd: bin\tests\Release\tests
